version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend-net

  backend:
    image: bibisam06/aldi:server
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - backend-net

volumes:
  redis-data:

networks:
  backend-net:
    driver: bridge
